password = "secret"

OPENAI_API_KEY="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"
